# ---------- Build Stage ----------
FROM node:18-alpine as builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

# ---------- Production Stage ----------
FROM node:18-alpine
WORKDIR /app
COPY --from=builder /app .

EXPOSE 5001
CMD ["node", "server.js"]